github_checks:
    annotations: false
comment: false
coverage:
  status:
    patch:
      default:
        target: 60%
    project:
      default:
        target: auto  # target is the base commit coverage
        threshold: 5%  # allow this little decrease on project
        base: auto
