# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 8
  stride: 4
# Network config
masknet:
  n_srcs: [2, 3, 4, 5]
  bn_chan: 128
  hid_size: 128
  chunk_size: 128
  hop_size: 64
  n_repeats: 8
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
  use_mulcat: false
# Training config
training:
  epochs: 200
  batch_size: 2
  num_workers: 2
  half_lr: yes
  lr_decay: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.00000
# Data config
data:
  train_dir: "data/{}speakers/wav8k/min/tr"
  valid_dir: "data/{}speakers/wav8k/min/cv"
  task: sep_count
  sample_rate: 8000
  seglen: 4.0
  minlen: 2.0
loss:
  lambda: 0.05
