training:
  epochs: 200
  batch_size: 256
  num_workers: 4
  half_lr: yes
  early_stop: yes
g_loss:
  l: 100
# Optim config
optim:
  optimizer: adam
  lr: 0.0001
  betas: [0.0, 0.9]
  weight_decay: 0.
# Data config
data:
  task: enh_single
  train_dir: data/wav16k/min/train-360
  valid_dir: data/wav16k/min/dev
  sample_rate: 16000
  n_src: 1
  segment: 1.024 # This parameter shouldn't be changed in training