encoder:
  enc_name : free
decoder:
  dec_name : free

# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 32
  stride: 16
# Network config
masknet:
  n_blocks: 6
  n_repeats: 2
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 1
  num_workers: 1
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  metadata_train_file: "D://libri2mix//mixtures//metadata//train-clean-100.csv"
  metadata_valid_file: "D://libri2mix//mixtures//metadata//test-clean.csv"
  metadata_test_file: "D://libri2mix//mixtures//metadata//dev-clean.csv"
  sample_rate: 16000
  mode: min
  sample_length: 4

