encoder:
  enc_name : free
decoder:
  dec_name : free

# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 32
  stride: 16
# Network config
masknet:
  n_blocks: 6
  n_repeats: 2
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 1
  num_workers: 1
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  mixtures_train_path : "D://libri2mix//16K//min//mixtures//train-clean-100"
  sources_train_path : "D://libri2mix//16K//min//sources//train-clean-100"
  mixtures_val_path : "D://libri2mix//16K//min//mixtures//dev-clean"
  sources_val_path : "D://libri2mix//16K//min//sources//dev-clean"
  sample_length: 4

