# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 3
  n_repeats: 2
  mask_act: relu
# Training config
training:
  epochs: 100
  half_lr: yes
  early_stop: yes
  max_norm: 5
  checkpoint: n
  continue_from:
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
  batch_size: 3
  num_workers: 4
