# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 21
  stride: 10
# Network config
masknet:
  n_blocks: 16
  n_repeats: 5
  mask_act: relu
  bn_chan: 512
  skip_chan: 0
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: no
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
