# Filterbank config
filterbank:
  stft_kernel_size: 4096
  stft_stride: 1024
# Network config
masknet:
  n_src: 4
  architecture: DCUNet-10
  fix_length_mode: pad
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  root: data
  input: mixture.wav
  output: vocals.wav
  sample_rate: 44100
  segment: 6.0
  
