# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS     ?=
SPHINXBUILD    ?= sphinx-build
SPHINXAPIBUILD = sphinx-apidoc
SOURCEDIR      = source
BUILDDIR       = build
CODEDIR        = ../asteroid
APIDOCOUT      = "$(SOURCEDIR)"/apidoc


# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

doc:
	@echo "Generating doc"
	@$(SPHINXAPIBUILD) -fTMe "$(CODEDIR)" -o "$(APIDOCOUT)"
