# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 6
  n_repeats: 2
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir : data/wav8k/min/train-360
  valid_dir : data/wav8k/min/dev
  sample_rate : 8000
  n_src : 2
  segment: 4