name: CI base testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  doctest:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # max-parallel: 6
      matrix:
        python-version: [3.6]  #, 3.7, 3.8]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
#    - name: Get pip cache
#      id: pip-cache
#      run: |
#        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"
#
#    - name: Cache pip
#      uses: actions/cache@v2
#      with:
#        path: ${{ steps.pip-cache.outputs.dir }}
#        key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.requires }}-pip-${{ hashFiles('requirements.txt') }}
#        restore-keys: |
#          ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.requires }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade --user pip --quiet
        python -m pip install numpy Cython --upgrade-strategy only-if-needed --quiet
        python -m pip install pytest coverage codecov --upgrade-strategy only-if-needed --quiet
        python -m pip install -r requirements.txt --quiet
        python -m pip install -r docs/requirements.txt --quiet
        python -m pip list
#        pip install --requirement ./requirements/base.txt --quiet  --find-links https://download.pytorch.org/whl/cpu/torch_stable.html --upgrade
#        pip install --requirement ./requirements/test.txt --quiet --upgrade-strategy only-if-needed
#        pip install tox coverage
#        python --version
#        pip --version
      shell: bash

    - name: Test with pytest and coverage
      run: |
        coverage run -m py.test tests
#        coverage report -m  # was is travis
    - name: Generate and upload the coverage report
      run: |
        coverage xml
        bash <(curl -s https://codecov.io/bash)

    - name: build docs
      run: |
        cd docs
        make html
        touch build/html/.nojekyll  # prevents use jekyll to build doc
