name: Version consistency

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
# Trigger the workflow on push or pull request
on:
  workflow_dispatch:
  # See here for scheduler events
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  # CRON 0 0 * * * means the first minute of the first hour every day.
  schedule:
  - cron:  '0 0 * * *'

jobs:
  src-test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]  #, 3.7, 3.8]
        pytorch-version: ["1.8.0", "nightly"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install libnsdfile
      run: |
        sudo apt update
        sudo apt install libsndfile1-dev libsndfile1

    - name: Install python dependencies
      env:
        TORCH_INSTALL: ${{ matrix.pytorch-version }}
      run: |
        python -m pip install --upgrade --user pip --quiet
        python -m pip install numpy Cython --upgrade-strategy only-if-needed --quiet
        if [ $TORCH_INSTALL == "1.8.0" ]; then
          INSTALL="torch==1.8.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html"
        else
          INSTALL="--pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html"
        fi
        python -m pip install $INSTALL
        python -m pip install -r requirements/dev.txt --quiet
        python --version
        pip --version
        python -m pip list
      shell: bash

    - name: Source code tests
      run: |
        RUN_SLOW=1 py.test tests/version_consistency
        echo "Just echo"
